"""empty message

Revision ID: 1bd289f61993
Revises: 
Create Date: 2016-03-03 00:04:20.562407

"""

# revision identifiers, used by Alembic.
revision = '1bd289f61993'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
