"""empty message

Revision ID: 878496c7f141
Revises: e52722131154
Create Date: 2016-03-09 00:38:56.428260

"""

# revision identifiers, used by Alembic.
revision = '878496c7f141'
down_revision = 'e52722131154'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
