"""empty message

Revision ID: 95e6a7dda3b6
Revises: 878496c7f141
Create Date: 2016-03-09 00:39:46.522268

"""

# revision identifiers, used by Alembic.
revision = '95e6a7dda3b6'
down_revision = '878496c7f141'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scheme', sa.Column('name', sa.String(length=64), nullable=False))
    op.add_column('scheme', sa.Column('ns_prefix', sa.String(length=512), nullable=False))
    op.add_column('scheme', sa.Column('ns_url', sa.String(length=512), nullable=False))
    op.drop_column('scheme', 'prefix')
    op.drop_column('scheme', 'uri')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scheme', sa.Column('uri', sa.VARCHAR(length=512), autoincrement=False, nullable=False))
    op.add_column('scheme', sa.Column('prefix', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.drop_column('scheme', 'ns_url')
    op.drop_column('scheme', 'ns_prefix')
    op.drop_column('scheme', 'name')
    ### end Alembic commands ###
