"""empty message

Revision ID: e52722131154
Revises: 1bd289f61993
Create Date: 2016-03-04 23:55:23.960482

"""

# revision identifiers, used by Alembic.
revision = 'e52722131154'
down_revision = '1bd289f61993'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scheme', sa.Column('namespaces', sa.Text(), server_default='', nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scheme', 'namespaces')
    ### end Alembic commands ###
